# Generated by Django 5.2.7 on 2025-10-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyntaxTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('tree_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntax_trees', to='translator_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pairs', to='translator_app.document')),
                ('target_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_pairs', to='translator_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='WordAnalysisEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=50)),
                ('morph', models.CharField(blank=True, max_length=200)),
                ('frequency', models.IntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_analysis_en', to='translator_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='WordAnalysisRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=50)),
                ('morph', models.CharField(blank=True, max_length=200)),
                ('frequency', models.IntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_analysis_ru', to='translator_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='WordDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0)),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='translator_app.wordanalysisen')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='translator_app.wordanalysisru')),
            ],
        ),
    ]
