# Generated by Django 5.1.7 on 2025-03-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=10)),
                ('dep', models.CharField(max_length=20)),
                ('head_text', models.CharField(max_length=100)),
                ('head_pos', models.CharField(max_length=10)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='linguistic_processor_app.sentence')),
            ],
        ),
    ]
