# Generated by Django 5.1.7 on 2025-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_processor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='dep',
            field=models.CharField(max_length=50),
        ),
    ]
