# Generated by Django 5.1.7 on 2025-04-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_processor_app', '0002_alter_token_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='definitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='is_known_word',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='synonyms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
