# Generated by Django 5.1.7 on 2025-04-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_processor_app', '0003_token_definitions_token_is_known_word_token_synonyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_known_word',
        ),
        migrations.AddField(
            model_name='token',
            name='antonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='semantic_relations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
