# Generated by Django 5.1.7 on 2025-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_processor_app', '0004_remove_token_is_known_word_token_antonyms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='semantic_relations',
        ),
        migrations.AddField(
            model_name='token',
            name='also_sees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='causes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='entailments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='holonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='hypernyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='hyponyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='meronyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='similar_tos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='token',
            name='verb_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
