# Generated by Django 5.1.7 on 2025-04-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_processor_app', '0005_remove_token_semantic_relations_token_also_sees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='similar_tos',
        ),
        migrations.RemoveField(
            model_name='token',
            name='verb_groups',
        ),
    ]
