# Generated by Django 5.1.7 on 2025-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic_processor_app', '0006_remove_token_similar_tos_remove_token_verb_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('char_count', models.IntegerField()),
                ('char_count_no_spaces', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('meaningful_word_count', models.IntegerField()),
                ('unique_word_count', models.IntegerField()),
                ('wateriness_percentage', models.FloatField()),
                ('classical_toughness', models.FloatField()),
                ('academic_toughness', models.FloatField()),
                ('grammatical_errors', models.IntegerField()),
                ('semantic_core', models.JSONField()),
            ],
        ),
    ]
