# Generated by Django 5.1.7 on 2025-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextmanagerapp', '0002_remove_article_analysis_result_posstats_wordanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sport',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posstats',
            name='pos_tag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wordanalysis',
            name='lemma',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wordanalysis',
            name='pos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wordanalysis',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
