# Generated by Django 5.1.6 on 2025-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=100)),
                ('part_of_speech1', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('article', 'Article'), ('numeral', 'Numeral'), ('participle', 'Participle'), ('gerund', 'Gerund'), ('infinitive', 'Infinitive')], max_length=20)),
                ('word2', models.CharField(max_length=100)),
                ('part_of_speech2', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('article', 'Article'), ('numeral', 'Numeral'), ('participle', 'Participle'), ('gerund', 'Gerund'), ('infinitive', 'Infinitive')], max_length=20)),
                ('collocation', models.CharField(max_length=200)),
                ('collocation_type', models.CharField(choices=[('adjective_order', 'Adjective Order'), ('noun_compound', 'Noun Compound'), ('preposition_phrase', 'Preposition Phrase'), ('verb_phrase', 'Verb Phrase'), ('article_usage', 'Article Usage'), ('numeral_usage', 'Numeral Usage'), ('pronoun_usage', 'Pronoun Usage'), ('participle_phrase', 'Participle Phrase'), ('adverb_usage', 'Adverb Usage'), ('infinitive_phrase', 'Infinitive Phrase'), ('gerund_phrase', 'Gerund Phrase')], max_length=50)),
            ],
        ),
    ]
