# Generated by Django 5.1.6 on 2025-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collocation',
            name='collocation_type',
            field=models.CharField(choices=[('noun_adjective', 'Noun + Adjective'), ('noun_preposition', 'Noun + Preposition'), ('noun_verb', 'Noun + Verb'), ('verb_adverb', 'Verb + Adverb'), ('verb_noun', 'Verb + Noun'), ('verb_pronoun', 'Verb + Pronoun'), ('verb_preposition', 'Verb + Preposition'), ('adjective_noun', 'Adjective + Noun'), ('adjective_adverb', 'Adjective + Adverb'), ('adjective_preposition', 'Adjective + Preposition'), ('adverb_verb', 'Adverb + Verb'), ('adverb_adjective', 'Adverb + Adjective'), ('adverb_adverb', 'Adverb + Adverb'), ('pronoun_verb', 'Pronoun + Verb'), ('pronoun_preposition', 'Pronoun + Preposition'), ('preposition_noun', 'Preposition + Noun'), ('preposition_pronoun', 'Preposition + Pronoun'), ('preposition_verb', 'Preposition + Verb'), ('numeral_noun', 'Numeral + Noun')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collocation',
            name='part_of_speech1',
            field=models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('ADP', 'Preposition'), ('CONJ', 'Conjunction'), ('INTJ', 'Interjection'), ('DET', 'Article'), ('NUM', 'Numeral'), ('PRT', 'Participle'), ('GER', 'Gerund'), ('INF', 'Infinitive')], max_length=4),
        ),
        migrations.AlterField(
            model_name='collocation',
            name='part_of_speech2',
            field=models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('ADP', 'Preposition'), ('CONJ', 'Conjunction'), ('INTJ', 'Interjection'), ('DET', 'Article'), ('NUM', 'Numeral'), ('PRT', 'Participle'), ('GER', 'Gerund'), ('INF', 'Infinitive')], max_length=4),
        ),
    ]
